mekomsolutions/openmrs-module-initializer

api/src/main/java/org/openmrs/module/initializer/InitializerActivator.java
api/src/main/java/org/openmrs/module/initializer/InitializerConstants.java
api/src/main/java/org/openmrs/module/initializer/api/CsvParserFactory.java
api/src/main/java/org/openmrs/module/initializer/api/InitializerService.java
api/src/main/java/org/openmrs/module/initializer/api/impl/InitializerServiceImpl.java
api/src/main/java/org/openmrs/module/initializer/api/impl/Utils.java
api/src/main/java/org/openmrs/module/initializer/api/program/ProgramCsvParser.java
api/src/main/java/org/openmrs/module/initializer/api/program/ProgramLineProcessor.java
api/src/test/java/org/openmrs/module/initializer/api/DomainProgramsInitializerServiceTest.java
api/src/test/resources/testAppDataDir/configuration/programs/programs.csv

* Add program CSV parsers 
* Add tests for program loading
* Add CSV file to keep the program meta-data

Add a new domain and implementation for Program

---

README.md
api/src/main/java/org/openmrs/module/initializer/InitializerConstants.java
api/src/main/java/org/openmrs/module/initializer/api/CsvParser.java
api/src/main/java/org/openmrs/module/initializer/api/loaders/ConceptsLoader.java
api/src/main/java/org/openmrs/module/initializer/api/loaders/DrugsLoader.java
api/src/main/java/org/openmrs/module/initializer/api/loaders/GlobalPropertiesLoader.java
api/src/main/java/org/openmrs/module/initializer/api/loaders/IdentifierSourcesLoader.java
api/src/main/java/org/openmrs/module/initializer/api/loaders/LocationsLoader.java
api/src/main/java/org/openmrs/module/initializer/api/loaders/OrderFrequenciesLoader.java
api/src/main/java/org/openmrs/module/initializer/api/loaders/PersonAttributeTypesLoader.java
api/src/main/java/org/openmrs/module/initializer/api/loaders/PrivilegesLoader.java
api/src/main/java/org/openmrs/module/initializer/api/loaders/ProgramWorkflowStatesLoader.java
api/src/main/java/org/openmrs/module/initializer/api/loaders/ProgramsLoader.java
api/src/main/java/org/openmrs/module/initializer/api/privileges/PrivilegeLineProcessor.java
api/src/main/java/org/openmrs/module/initializer/api/privileges/PrivilegesCsvParser.java
api/src/test/java/org/openmrs/module/initializer/api/PrivilegesLoaderIntegrationTest.java
api/src/test/java/org/openmrs/module/initializer/api/loaders/LoadersIntegrationTest.java
api/src/test/resources/testAppDataDir/configuration/drugs/drugs.csv
api/src/test/resources/testAppDataDir/configuration/privileges/privileges.csv
readme/priv.md

* Implementation of Privilege Domain.
* Add Integration test for privilege domain implementation.

Privilege domain Implementation 

---

api/src/main/java/org/openmrs/module/initializer/api/Utils.java
api/src/main/java/org/openmrs/module/initializer/api/roles/RoleLineProcessor.java
api/src/test/java/org/openmrs/module/initializer/api/RolesLoaderIntegrationTest.java
api/src/test/resources/testAppDataDir/configuration/roles/roles.csv
readme/roles.md

- Fetching role form uuid.
- Fetching inherited roles from uuid.
- Fetching privileges from uuid.

OPENMRS-74: Roles to support UUIDs.

---

api/src/main/java/org/openmrs/module/initializer/api/drugs/DrugLineProcessor.java

Ticket : https://mekomsolutions.atlassian.net/browse/OPENMRS-79

OPENMRS-79 NoSuchMethodError: getDrugByNameOrId when loading Drugs 

---

api/src/main/java/org/openmrs/module/initializer/api/InitializerServiceImpl.java

Resolves #32 using Oracle suggested method of URI and Path.resolve() cat

[#32] Fix for Windows path issue in tests.

---

api-2.3/src/test/java/org/openmrs/module/initializer/api/loaders/LoadersIntegrationTest.java
api/src/main/java/org/openmrs/module/initializer/Domain.java
api/src/main/java/org/openmrs/module/initializer/api/mdm/MetadataTermMappingsLineProcessor.java
api/src/main/java/org/openmrs/module/initializer/api/mds/MetadataSetLineProcessor.java
api/src/main/java/org/openmrs/module/initializer/api/mds/MetadataSetMemberLineProcessor.java
api/src/main/java/org/openmrs/module/initializer/api/mds/MetadataSetMembersCsvParser.java
api/src/main/java/org/openmrs/module/initializer/api/mds/MetadataSetMembersLoader.java
api/src/main/java/org/openmrs/module/initializer/api/mds/MetadataSetsCsvParser.java
api/src/main/java/org/openmrs/module/initializer/api/mds/MetadataSetsLoader.java
api/src/test/java/org/openmrs/module/initializer/api/MetadataSetMembersLoaderIntegrationTest.java
api/src/test/java/org/openmrs/module/initializer/api/MetadataSetsLoaderIntegrationTest.java
api/src/test/resources/test-hibernate.cfg.xml
api/src/test/resources/testAppDataDir/configuration/metadatasetmembers/metadatasetmembers.csv
api/src/test/resources/testAppDataDir/configuration/metadatasets/metadatasets.csv
api/src/test/resources/testdata/test-metadata-sets.xml

Ticket: https://github.com/mekomsolutions/openmrs-module-initializer/issues/48

[#48] Support for MetadataSet and MetadataSetMember.

---

README.md
api/src/main/java/org/openmrs/module/initializer/api/loc/LocationLineProcessor.java
api/src/main/java/org/openmrs/module/initializer/api/utils/LocationTagListParser.java
api/src/test/java/org/openmrs/module/initializer/api/LocationsLoaderIntegrationTest.java
api/src/test/resources/testAppDataDir/configuration/locations/locations.csv
readme/loc.md

[#44] Location domain to support for 'Tag|' headers.

---

api/src/main/java/org/openmrs/module/initializer/api/form/BahmniFormsLoader.java
api/src/test/java/org/openmrs/module/initializer/api/form/BahmniFormsLoaderIntegrationTest.java
pom.xml

- Upgrade to bahmni.ie.apps 1.1.0-SNAPSHOT
- Update BahmniForms loader

IE-APPS: Upgrade to bahmni.ie.apps 1.1.0-SNAPSHOT

---

api/src/main/java/org/openmrs/module/initializer/api/form/BahmniFormsLoader.java
api/src/test/java/org/openmrs/module/initializer/api/form/BahmniFormsLoaderIntegrationTest.java
api/src/test/resources/testAppDataDir/configuration/bahmniforms/test_form1.json
api/src/test/resources/testdata/testBahmniforms/test_form1_updated.json

https://mekomsolutions.atlassian.net/browse/C2C-18

C2C-18: Use Bahmni form uuid value if provided in JSON

---

README.md
api/src/main/java/org/openmrs/module/initializer/InitializerActivator.java
api/src/main/java/org/openmrs/module/initializer/InitializerConfig.java
api/src/main/java/org/openmrs/module/initializer/InitializerConstants.java
api/src/main/java/org/openmrs/module/initializer/api/InitializerService.java
api/src/main/java/org/openmrs/module/initializer/api/InitializerServiceImpl.java
api/src/test/java/org/openmrs/module/initializer/InitializerActivatorTest.java
api/src/test/java/org/openmrs/module/initializer/api/MockLoader.java
readme/rtprops.md

[#108] Support configuration of different loading modes at startup.

---

api/src/main/java/org/openmrs/module/initializer/api/ot/OrderTypeLineProcessor.java

[#116] OrderTypeLineProcessor to not attempt to validate the Java class name.

---

api/src/test/java/org/openmrs/module/initializer/api/ConceptsLoaderIntegrationTest.java
readme/concepts.md

Related to https://github.com/mekomsolutions/openmrs-module-initializer/pull/123

Updating READMEs about referencing nested concepts by name.

---

validator-first-dependency/src/main/resources/moduleApplicationContext.xml
validator/pom.xml

[#130] Validator to package providermanagement-api JAR.

---

api/src/main/java/org/openmrs/module/initializer/InitializerConfig.java
api/src/test/java/org/openmrs/module/initializer/InitializerActivatorTest.java
readme/rtprops.md

[#149] Allow InitializerConfig properties to be set from System Properties.

---

.github/workflows/build-and-test.yml

Also updates to use Eclipse Temurin, which has replaced AdoptOpenJDK

Trigger GitHub Actions on PR as well as push.

---

api-2.3/src/test/java/org/openmrs/module/initializer/api/loaders/LoadersOrderTest.java
api/src/main/java/org/openmrs/module/initializer/Domain.java
api/src/main/java/org/openmrs/module/initializer/api/loaders/LiquibaseLoader.java
api/src/test/java/org/openmrs/module/initializer/DomainBaseModuleContextSensitiveTest.java
api/src/test/java/org/openmrs/module/initializer/api/LiquibaseLoaderIntegrationTest.java
api/src/test/resources/testAppDataDir/configuration/liquibase/concepts.xml
api/src/test/resources/testAppDataDir/configuration/liquibase/liquibase.xml
readme/liquibase.md

[#101]: Adding domain for Liquibase changesets

---

README.md
api/src/main/java/org/openmrs/module/initializer/api/utils/Utils.java
api/src/test/java/org/openmrs/module/initializer/api/UtilsTest.java

[#194] Concept references should support names in locales other than the default locale

---

api/src/main/java/org/openmrs/module/initializer/api/fhir/cs/FhirConceptSourceCsvParser.java
api/src/main/java/org/openmrs/module/initializer/api/fhir/cs/FhirConceptSourceLineProcessor.java
api/src/main/java/org/openmrs/module/initializer/api/fhir/cs/FhirConceptSourcesLoader.java
api/src/main/java/org/openmrs/module/initializer/api/fhir/pis/FhirPatientIdentifierSystemCsvParser.java
api/src/main/java/org/openmrs/module/initializer/api/fhir/pis/FhirPatientIdentifierSystemLineProcessor.java
api/src/main/java/org/openmrs/module/initializer/api/fhir/pis/FhirPatientIdentifierSystemLoader.java
api/src/test/java/org/openmrs/module/initializer/api/FhirConceptSourcesLoaderIntegrationTest.java
api/src/test/java/org/openmrs/module/initializer/api/FhirPatientIdentifierSystemIntegrationTest.java
api/src/test/java/org/openmrs/module/initializer/api/UtilsTest.java
api/src/test/resources/testAppDataDir/configuration/fhirconceptsources/conceptsources.csv
api/src/test/resources/testAppDataDir/configuration/fhirpatientidentifiersystems/identifiersystems.csv
pom.xml
readme/fhir.md

NOTE:  Creating this as a Draft PR, as this depends on https://issues.openmrs.org/browse/FM2-518
We will also want to do a release of FHIR, and then update the POM in this PR to reflect the release that the above issue ends up in, whether 1.5.2 or 1.6.0.  @ibacher FYI, please have a look.

Initializer should save FHIR concept sources via a Service not via a DAO directly

---

README.md

Ticket: https://issues.openmrs.org/browse/RA-1994

RA-1994: Updating 2.4.0 release notes.

---

api-2.4/src/main/java/org/openmrs/module/initializer/api/logging/InitializerLogConfigurator2_4.java
api/src/main/java/org/openmrs/module/initializer/InitializerActivator.java
api/src/main/java/org/openmrs/module/initializer/api/loaders/BaseInputStreamLoader.java
api/src/main/java/org/openmrs/module/initializer/api/logging/InitializerLogConfigurator2_0.java
api/src/test/java/org/openmrs/module/initializer/api/JsonKeyValuesLoaderIntegrationTest.java
readme/rtprops.md

`initializer.logging.*` properties are expected in the code
See more details on Slack here: https://openmrs.slack.com/archives/CPC20CBFH/p1672332612265309

Logging *up* to specified level (and not just at specified level).

---

api/src/main/java/org/openmrs/module/initializer/api/fhir/pis/FhirPatientIdentifierSystemCsvParser.java
api/src/main/java/org/openmrs/module/initializer/api/fhir/pis/FhirPatientIdentifierSystemLineProcessor.java

Followup on https://github.com/mekomsolutions/openmrs-module-initializer/pull/222
Hi @ibacher, somehow we missed out this one. Could you merge it in as well? Thanks.

Fix FHIR domains to properly use @OpenmrsProfile

---

api-2.4/src/main/java/org/openmrs/module/initializer/api/logging/InitializerLogConfigurator2_4.java
api/src/main/java/org/openmrs/module/initializer/InitializerActivator.java
api/src/main/java/org/openmrs/module/initializer/InitializerMessageSource.java
api/src/main/java/org/openmrs/module/initializer/api/CsvParser.java
api/src/main/java/org/openmrs/module/initializer/api/logging/InitializerLogConfigurator2_0.java
api/src/test/java/org/openmrs/module/initializer/InitializerActivatorTest.java
api/src/test/java/org/openmrs/module/initializer/api/CohortTypeLoaderIntegrationTest.java
api/src/test/java/org/openmrs/module/initializer/api/InitializerServiceImplTest.java
api/src/test/java/org/openmrs/module/initializer/api/c/ConceptsCsvParserTest.java
readme/validator.md
validator/pom.xml
validator/src/main/java/org/openmrs/module/initializer/validator/ConfigurationTester.java
validator/src/main/java/org/openmrs/module/initializer/validator/Validator.java

Issue: https://github.com/mekomsolutions/openmrs-module-initializer/issues/209
Depends on https://github.com/openmrs/openmrs-core/pull/4250

[#209] Fixing Validator.

---

api/src/main/java/org/openmrs/module/initializer/api/drugs/DrugLineProcessor.java

issue: https://github.com/mekomsolutions/openmrs-module-initializer/issues/209

[#209] DrugLineProcessor to require a concept drug as documented in 'readme/drugs.md'.

---

api/src/main/java/org/openmrs/module/initializer/api/InitializerServiceImpl.java
api/src/main/resources/moduleApplicationContext.xml

[#211] Fixes bean wiring, removing deprecated XML syntax and removes @Autowired from OpenMRS service.

---

.github/workflows/build-test.yml
api-2.3/pom.xml
api-2.3/src/test/java/org/openmrs/module/initializer/DomainBaseModuleContextSensitive_2_3_Test.java
api/src/test/java/org/openmrs/module/initializer/api/UtilsTest.java
api/src/test/java/org/openmrs/module/initializer/api/c/ConceptAttributeLineProcessorTest.java
api/src/test/java/org/openmrs/module/initializer/api/c/ConceptsCsvParserTest.java
api/src/test/java/org/openmrs/module/initializer/api/loc/LocationAttributeLineProcessorTest.java
pom.xml

[#231] Initializer to build against Java 11

---

api-2.3/src/test/java/org/openmrs/module/initializer/DomainBaseModuleContextSensitive_2_3_Test.java
validator/src/main/java/org/openmrs/module/initializer/validator/ConfigurationTester.java

[#209] Fix Validator rollback errors by adding @Rollback(false) annotation.

---

readme/ampathformstranslations.md

[#221] Update ampathformstranslation.md

---

README.md
api-2.2/pom.xml
api-2.3/pom.xml
api-2.4/pom.xml
api-bahmni/pom.xml
api/pom.xml
omod/pom.xml
pom.xml
readme/validator.md
validator-first-dependency/pom.xml
validator/pom.xml

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-90

Release 2.5.1

---

README.md
api-2.2/pom.xml
api-2.3/pom.xml
api-2.4/pom.xml
api-bahmni/pom.xml
api/pom.xml
omod/pom.xml
pom.xml
readme/validator.md
validator-first-dependency/pom.xml
validator/pom.xml

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-168

Release 2.5.2

---

readme/csv_conventions.md

Minor edits to improve grammar and spelling while maintaining the meaning.

Rephrasing csv_conventions.md.

---

omod/src/main/java/org/openmrs/module/initializer/web/controller/InitializerController.java

Minor edits to improve grammar while maintaining the meaning.

Improved `InitializerController` JavaDocs.

---

api-2.4/pom.xml
omod/src/main/resources/config.xml
pom.xml

- Makes iniz aware of billing module.

Iniz aware of the billing module

---

README.md
pom.xml

Reverts mekomsolutions/openmrs-module-initializer#274

Revert "Bump OCL version from 1.2.9 to 2.3.0"

---

README.md
api/src/main/java/org/openmrs/module/initializer/api/drugs/DrugsCsvParser.java
api/src/main/java/org/openmrs/module/initializer/api/drugs/IngredientsDrugLineProcessor.java
api/src/test/java/org/openmrs/module/initializer/api/DrugsLoaderIntegrationTest.java
api/src/test/resources/testAppDataDir/configuration/drugs/drugsWithIngredients.csv
readme/drugs.md

See:  https://github.com/mekomsolutions/openmrs-module-initializer/issues/300
@mks-d / @ibacher - not sure who the best people are to review Iniz PRs these days, but please add anyone as appropriate.

#300 - Support loading drug ingredients
