api/src/main/java/org/openmrs/module/initializer/api/OrderableCsvFile.java, api/src/main/java/org/openmrs/module/initializer/api/loaders/BaseCsvLoader.java, api/src/main/java/org/openmrs/module/initializer/api/utils/IgnoreBOMInputStream.java, api/src/test/java/org/openmrs/module/initializer/api/c/ConceptsCsvParserTest.java, api/src/test/resources/org/openmrs/module/initializer/include/csv/with_bom.csv
This issue was [reported on Slack](https://openmrs.slack.com/archives/CPC20CBFH/p1586459401056200). Just adds a simple wrapper for an `InputStream` which ignores the UTF Byte Order Mark sequence if it is erroneously added to the file.
PS I'm 90% sure that the test I've added tests what I wanted it to, but it's really disconcerting that it throws an exception...
=> Add support for CSVs containing a UTF-8 BOM.

readme/pit.md
As per Slack conversation:
https://openmrs.slack.com/archives/CPC20CBFH/p1586850691014900£
> One small thing I’ve noticed though: the headers in the readme are missing the Required field, and it happens that this field is the only one that is mandatory (other than the name) in order to successfully save the line.
> So 2 ways: either to specify this in the Readme, or we consider a default value when the field value is not provided.
Went for defaulting to `FALSE` when the field value is not provided.
=> PatientIdentifierType#required better documented.

api-2.2/pom.xml, api-2.3/pom.xml, api/pom.xml, omod/src/main/resources/config.xml, pom.xml
As part of this PR below things are done:
=> Upgrade Bahmni Appointments dependency to 1.2.1.

api/src/main/java/org/openmrs/module/initializer/InitializerMessageSource.java, api/src/test/java/org/openmrs/module/initializer/InitializerMessageSourceIntegrationTest.java, api/src/test/resources/testAppDataDir/configuration/messageproperties/metadata_fr.properties
I was working with PIH to help them track down an issue where single-quotes in some messages were disappearing even though they had been around for quite a while. The change introduced in their environment was that these values were being loaded by the `InitializerMessageSource`. That makes perfect sense, since the `InitializerMessageSource` loads every property as a [`MessageFormat`](https://docs.oracle.com/javase/7/docs/api/java/text/MessageFormat.html) object and `MessageFormat` objects treat single-quotes as a special character requiring them to be escaped.
The issue is that this hadn't happened prior to using Initializer and there aren't any hacks in to OpenMRS codebase to escape single-quotes. What appears to have happened is that Spring has introduced a certain API quirk (you can …
=> InitializerMessageSource consistent with Spring MessageSources.

api-2.2/pom.xml, api-2.2/src/test/java/org/openmrs/module/initializer/attributes/types/AttributeTypesProxyServiceTest.java, api-2.3/pom.xml, api/pom.xml, api/src/test/java/org/openmrs/module/initializer/api/attributes/types/AttributeTypesProxyServiceTest.java, omod/pom.xml, pom.xml
The main fix introduced here is to ensure that all context sensitive tests extend `DomainBaseModuleContextSensitiveTest`, which was not the case for the 2 `AttributeTypesProxyServiceTest` classes.
This fix also updates the poms by consolidating common dependencies in the parent pom, updating them to provided scope, and removing the omod dependency from the api project(s).  There is also some whitespace formatting to the pom files - please ignore white space changes when reviewing.  These fixes enable the build to pass on my environment.
=> [#81] Fix failing builds in some environments.

README.md, api-2.3/src/test/java/org/openmrs/module/initializer/api/loaders/LoadersIntegrationTest.java, api/src/main/java/org/openmrs/module/initializer/Domain.java, api/src/main/java/org/openmrs/module/initializer/api/form/HtmlFormsLoader.java, api/src/test/java/org/openmrs/module/initializer/DomainBaseModuleContextSensitiveTest.java, api/src/test/java/org/openmrs/module/initializer/api/form/HtmlFormsLoaderIntegrationTest.java, api/src/test/resources/test-hibernate.cfg.xml, api/src/test/resources/testAppDataDir/configuration/htmlforms/allAttributeForm.xml, omod/src/main/resources/config.xml, pom.xml, readme/htmlforms.md
This adds a new "htmlforms" domain that is supported if the htmlformentry module is installed.  This follows the model of the htmlformentryui module, which established the pattern and naming convention of attributes on the <htmlform> tag to enable specification of the metadata required to create and update an htmlform in the database.
=> [#80] Support for htmlforms.

api/src/main/java/org/openmrs/module/initializer/api/loaders/JsonKeyValuesLoader.java, api/src/test/java/org/openmrs/module/initializer/api/JsonKeyValuesLoaderIntegrationTest.java
jsonkeyvalues domain loader should not process checksums for loaded files since the data is never persisted but rather cached and should always be reloaded.
=> 'jsonkeyvalues' domain to skip writing checksums.

api/src/main/java/org/openmrs/module/initializer/api/programs/ProgramLineProcessor.java, readme/prog.md
I assume these were left off intentionally with the feeling that they should really be populated from Concept.  But we have existing program data that we are trying to migrate over to manage going forward with Iniz, and these have populated names and descriptions that vary from Concept names.
This also has the nice benefit of making the source CSV readable, as there are actually columns that describe what each row represents, rather than simply a collection of uuid references.
@mks-d let me know what you think.
=> [#102] Programs domain to support name and description headers.

api-2.3/src/main/java/org/openmrs/module/initializer/api/datafilter/mappings/DataFilterMappingsCsvParser.java, api/src/main/java/org/openmrs/module/initializer/api/CsvParser.java, api/src/main/java/org/openmrs/module/initializer/api/privileges/PrivilegesCsvParser.java, api/src/main/java/org/openmrs/module/initializer/api/programs/workflows/states/ProgramWorkflowStatesCsvParser.java, api/src/main/java/org/openmrs/module/initializer/api/roles/RolesCsvParser.java, api/src/test/java/org/openmrs/module/initializer/api/DrugsLoaderIntegrationTest.java, api/src/test/resources/testAppDataDir/configuration/drugs/drugs.csv
It seems that the existing system is intentionally allowing CSV rows to constain just an identifier (uuid) and a void/retire flag set to true, and all other columns left blank, in order to allow voiding/retiring existing data without having full details.  Personally I don't love this feature, but it seems ingrained in the unit tests and there may be groups relying upon it, so I left it in place for backwards compatibility.
So, what this PR does is ensure that if the row represents a _new_ object being saved to the DB, that it _is_ populated with the full row details being saved, as if this does not happen then things fail badly on most objects.  The way I determined this was checking if an object has an id.  If an id exists, I am assuming it represents an existing loaded object.  There …
=> [#106] Parsers to fill new retired/voided entities.

README.md, api/src/main/java/org/openmrs/module/initializer/api/BaseAttributeLineProcessor.java, api/src/main/java/org/openmrs/module/initializer/api/loc/LocationLineProcessor.java, api/src/test/java/org/openmrs/module/initializer/api/loc/LocationAttributeLineProcessorTest.java, api/src/test/java/org/openmrs/module/initializer/api/loc/LocationLineProcessorTest.java, readme/loc.md
Part of https://github.com/mekomsolutions/openmrs-module-initializer/issues/110
=> Leave existing non-specified attributes and location tags intact when loading

api/src/main/java/org/openmrs/module/initializer/InitializerActivator.java, api/src/main/java/org/openmrs/module/initializer/InitializerMessageSource.java, api/src/main/java/org/openmrs/module/initializer/api/ConfigDirUtil.java, api/src/main/resources/moduleApplicationContext.xml, api/src/test/java/org/openmrs/module/initializer/AddressHierarchyMessagesLoadingTest.java, api/src/test/java/org/openmrs/module/initializer/DomainBaseModuleContextSensitiveTest.java, api/src/test/java/org/openmrs/module/initializer/InitializerMessageSourceIntegrationTest.java, api/src/test/java/org/openmrs/module/initializer/InitializerMessageSourceTest.java, api/src/test/resources/TestingApplicationContext.xml, api/src/test/resources/messages.properties, api/src/test/resources/messages_fr.properties, api/src/test/resources/messages_fr_FR.properties, api/src/test/resources/messages_ht.properties, api/src/test/resources/testAppDataDir/configuration/messageproperties/metadata_en.properties, api/src/test/resources/testAppDataDir/configuration/messageproperties/metadata_es.properties, api/src/test/resources/testAppDataDir/configuration/messageproperties/metadata_fr.properties
This PR undertakes a reasonably sizeable overhaul of the InitializerMessageSource.  The initial impetus for this was to investigate and fix issues related to appropriate "fallback" messages not being rendered when expected.  For example, we had situations where message codes were being rendered even when messages exist for the "default locale" (i.e. English).  Upon starting to investigate, we encountered a number of other examples of unexpected behavior, which we attributed to limitations in the existing OpenMRS and Spring message source implementations around precedence of message loading in both Spring and Openmrs message sources, and our delegation of message loading between custom source and parent source.
Ultimately, we concluded that the most effective means of ensuring consistent, …
=> [#155] Overhaul of InitializerMessageSource.

README.md, api/src/main/java/org/openmrs/module/initializer/InitializerMessageSource.java, api/src/test/java/org/openmrs/module/initializer/InitializerMessageSourceTest.java
This fixes a bug identified following the merging of the original PR.  The unit tests were failing in CI due to a previously unidentified that occurs if the directory contaiining message properties has an underscore in the name.  This commit adds a unit test that reproduces this bug and a patch that fixes it.
=> Issue 155 fix

api/src/main/java/org/openmrs/module/initializer/api/c/ConceptsCsvParser.java
issue: #136
After testing the latest Iniz snapshot on an implementation with multiple concepts being reloaded, random `Concept`s fail to load because their existing names are not yet updated by the time new names are being saved. This happens especially when the existing name(s) are being voided and new names added. 
Consider a `Concept` with 3 names `Green`, `Yellow` and `Red` in a single locale being reloaded and having random uuids.
The 3 existing names should be voided and 3 new names recreated having seeded uuids.
Since saving and/or updating concept names happens randomly, it is possible that the new name Yellow with a seeded uuid gets saved before the existing name Yellow with a random uuid is updated as voided. In which case a `DuplicateConceptNameException` error occurs resulting …
=> [#136] Existing concept names to be resaved before adding new ones.

readme/ocl.md
Added: 
- Benefits of this approach
- How to get .zip from OCL
- Reference for the RefApp /ocl config file
=> Improved documentation for getting & using .zip for /ocl

api/src/main/java/org/openmrs/module/initializer/api/OrderedCsvFile.java, api/src/main/java/org/openmrs/module/initializer/api/loaders/BaseInputStreamLoader.java
Use [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) feature to close resources.
For `BaseInputStreamLoader`, it is not needed to use `IOUtils.closeQuietly(is)` since it's done implicitly with `try(...)`.
=> Use InputStream auto-close feature.

README.md, api/src/main/java/org/openmrs/module/initializer/InitializerMessageSource.java, api/src/test/java/org/openmrs/module/initializer/InitializerMessageSourceIntegrationTest.java, api/src/test/java/org/openmrs/module/initializer/InitializerMessageSourceTest.java
=> [#212] Locale-unspecified message properties to default to 'en' messages.

README.md, api-2.4/src/main/java/org/openmrs/module/initializer/api/logging/InitializerLogConfigurator2_4.java, api-2.4/src/main/java/org/openmrs/module/initializer/api/logging/InitializerLogConfigurator2_4Test.java, api/src/main/java/org/openmrs/module/initializer/api/logging/InitializerLogConfigurator2_0.java, api/src/test/java/org/openmrs/module/initializer/api/logging/InitializerLogConfigurator2_0Test.java
PR to Fix an issue included in my previous PR concerning log management:
in core 2.3, log level is configured using reflection as  some classes are not available.
In the previous PR I used a wrong method signature for `org.apache.log4j.varia.LevelRangeFilter`.
This PR will fix this issued and add a Unit Test.
=> Fix logging to use logger levels instead of filters

api/src/main/java/org/openmrs/module/initializer/api/fhir/cs/FhirConceptSourceCsvParser.java, api/src/main/java/org/openmrs/module/initializer/api/fhir/cs/FhirConceptSourceLineProcessor.java, api/src/main/java/org/openmrs/module/initializer/api/fhir/cs/FhirConceptSourcesLoader.java, api/src/main/java/org/openmrs/module/initializer/api/fhir/pis/FhirPatientIdentifierSystemCsvParser.java, api/src/main/java/org/openmrs/module/initializer/api/fhir/pis/FhirPatientIdentifierSystemLineProcessor.java, api/src/main/java/org/openmrs/module/initializer/api/fhir/pis/FhirPatientIdentifierSystemLoader.java, api/src/test/java/org/openmrs/module/initializer/DomainBaseModuleContextSensitiveTest.java
Per [this insight](https://github.com/mekomsolutions/openmrs-module-initializer/pull/220#discussion_r1114095110), removing `@Component` from some places it shouldn't be.
=> Fix FHIR domains to properly use @OpenmrsProfile

api/src/main/java/org/openmrs/module/initializer/api/InitializerServiceImpl.java, api/src/main/resources/moduleApplicationContext.xml
This is a followup PR to address a runtime bug caused by the InitializerDAO not being set.
Issue: https://github.com/mekomsolutions/openmrs-module-initializer/issues/211
=> [#211] Undo InitializerDAO XML injection in favour of autowiring injection.

README.md, api/src/main/java/org/openmrs/module/initializer/api/loaders/AmpathFormsTranslationsLoader.java, api/src/test/java/org/openmrs/module/initializer/api/form/AmpathFormsTranslationsLoaderIntegrationTest.java, api/src/test/resources/testAppDataDir/configuration/ampathformstranslations/test_form_translations_fr.json
Issue #221
This enhancement forces `ampathformtranslations` to be always reloaded because the affected message properties need to be reloaded at every startup.
=> [#221] Support translating AMPATH Form Names via ampathformtranslations domain

api/src/main/java/org/openmrs/module/initializer/api/loaders/AmpathFormsTranslationsLoader.java, api/src/test/resources/testAppDataDir/configuration/ampathformstranslations/test_form_translations_fr.json, validator/pom.xml, validator/src/main/java/org/openmrs/module/initializer/validator/ConfigurationTester.java
While putting Validator to stress test, it could randomly fail because of some hibernate indexing during some `@After` test method. To resolve that I've had to add the following to the hibernate runtime config `hibernate.search.indexing_strategy = manual`. The offending full stack trace looks like [this](https://pastebin.com/raw/rm7Gsjrx) and is `Caused by: org.hibernate.LazyInitializationException: could not initialize proxy - no Session`
=> OZ-90: Validator on OpenMRS to 2.3.6 + fix LazyInitializationException on successful validations.

validator/src/main/java/org/openmrs/module/initializer/validator/ConfigurationTester.java
This is a simple enhance to ensure that the Validator can clean up its environment (e.g stopping its containers) before exiting.
=> Validator to cleanup before exiting

validator/pom.xml
This PR fixes the silently failing `org.openmrs.module.metadatamapping.MetadataSource` specific `metadatasharing` domain issue on the validator.
Discovered while testing Ref App configuration here; https://github.com/openmrs/openmrs-distro-referenceapplication/pull/717
=> RA-2023: Bumping Validator's metadatamapping to 1.6.0 and metadatasharing to 1.9.0.

api/src/main/java/org/openmrs/module/initializer/api/c/ConceptNumericLineProcessor.java, api/src/test/java/org/openmrs/module/initializer/api/c/ConceptNumericLineProcessorTest.java
=> [#257] Provision to allow overriding concepts' datatype to 'Numeric'.

api-2.3/src/main/java/org/openmrs/module/initializer/api/queues/QueueLineProcessor.java, api-2.3/src/test/java/org/openmrs/module/initializer/api/queues/QueueLoaderIntegrationTest.java, api-2.3/src/test/resources/testAppDataDir/configuration/queues/queues.csv, api/src/test/resources/testdata/test-queues.xml, pom.xml, readme/queues.md
@mseaton , I just added the ability to load the new queue.status_concept_set field that you added as part of the O3-2446 ticket. Thanks!
=> O3-2446: 'queues' domain to support loading Status and Priority entries.

README.md, validator/src/main/java/org/openmrs/module/initializer/validator/ConfigurationTester.java
=> [#265]: Validator to properly shutdown, so not to fail further invocations on the same JVM process.

api/src/main/java/org/openmrs/module/initializer/liquibase/DeleteDomainChecksumsChangeset.java
Fix NPE issue originating from `DeleteDomainChecksumsChangeset`. See https://github.com/openmrs/openmrs-core/pull/4637#issuecomment-2132856318
```
ERROR - Slf4JLogger.log(39) |2024-05-27T01:05:29,953| ChangeSet liquibase.xml::delete-concepts-checksums-20211025::iniz encountered an exception.
java.lang.NullPointerException: null
at java.base/java.util.Objects.requireNonNull(Objects.java:209) ~[?:?]
at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:263) ~[?:?]
at java.base/java.nio.file.Path.of(Path.java:147) ~[?:?]
at java.base/java.nio.file.Paths.get(Paths.java:69) ~[?:?]
at org.openmrs.module.initializer.api.ConfigDirUtil.<init>(ConfigDirUtil.java:72) ~[initializer-api-2.6.0.jar:?]
at org.openmrs.module.initializer.api.ConfigDirUtil.<init>(ConfigDirUtil.java:81) …
```
=> TRUNK-6208: Fix `null` config directory path in `DeleteDomainChecksumsChangeset`.

api-2.2/pom.xml, api-2.3/pom.xml, api-2.4/pom.xml, api-2.5/pom.xml, api-bahmni/pom.xml, api/pom.xml, omod/pom.xml, pom.xml, readme/validator.md, validator-first-dependency/pom.xml, validator/pom.xml
Refer to the conversation at https://talk.openmrs.org/t/o3-and-3-0-0-its-time-to-say-goodbye-to-the-beta/43054/4?u=mksd
=> Prepare for next development iteration

.github/workflows/build-test-publish.yml, .github/workflows/build-test.yml
So, the GitHub Actions jobs for this repo no longer work, since the `master` branch was renamed to `main`. This seems to be why 2.7.0 isn't actually released. Not sure how to fix that...
=> GitHub Actions to work on branch `main`.

README.md, api/src/main/java/org/openmrs/module/initializer/api/loaders/AmpathFormsLoader.java, api/src/main/java/org/openmrs/module/initializer/api/loaders/AmpathFormsTranslationsLoader.java, api/src/test/java/org/openmrs/module/initializer/api/form/AmpathFormsTranslationsLoaderIntegrationTest.java, pom.xml, readme/ampathforms.md
Added support to reload the Ampath Forms translations every time a form is changed.
- Added checksums files to  Ampath Forms translations.
- Remove the check sums for the Ampath Forms translations when a new Ampath Forms is loaded if already exist translation for an older version.
=> Added support to reload the Ampath Forms translations 

.vscode/settings.json, api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/PaymentModesCsvParser.java, api-2.4/src/main/java/org/openmrs/module/initializer/api/billing/PaymentModesLineProcessor.java, api-2.4/src/test/java/org/openmrs/module/initializer/api/PaymentModesLoaderIntegrationTest.java, api-2.4/src/test/resources/testAppDataDir/configuration/paymentmodes/paymentModes.csv, api/src/main/java/org/openmrs/module/initializer/api/CsvParser.java, api/src/test/java/org/openmrs/module/initializer/api/ProgramWorkflowStatesLoaderIntegrationTest.java, api/src/test/java/org/openmrs/module/initializer/api/ProgramWorkflowsLoaderIntegrationTest.java, api/src/test/java/org/openmrs/module/initializer/api/RelationshipTypesLoaderIntegrationTest.java, pom.xml, validator/pom.xml
The CSV parser should persist objects once files in a domain have been processed. Currently, there's a bug where the last `Privilege` isn't being persisted and this PR addresses it.
I have removed some Assertions in `PaymentModesLoaderIntegrationTest` as it references some attributes that have to be saved before.....We will work on refactoring the PaymentModeAttributeType domain
see https://openmrs.atlassian.net/browse/O3-3972
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`
existing code that was well tested you do not have to add tests)
No? -> write tests and add them to this commit `git add . && git commit --amend`
added all formatting changes to my …
=> #277 - CSV parser should save cached objects once file has been loaded.

README.md, pom.xml
OCL version `2.3.0` has a check on ConceptNames None, a check that doesn’t exist in the current dependency version `1.2.9` which causes build failures when adding new concepts.
This pr attempts to fix this issue.
=> Bump OCL version from 1.2.9 to 2.3.0

README.md
I recently created a training video in English & French explaining the basics about editing/managing Iniz config files. Since the youtube videos already have a combined 300+ views in just 3 weeks, I think this training is an unmet need and would be good to include in the README to reach a wider audience.
Specifically this video looks at real example config files for locations, drugs, forms, and form translations, with live-time editing shown. 
I added this under a new "Useful Resources" section so I could also include the UUID Generator website link, since many people don't know about it and it has been an extremely useful resource to me in all the UUID columns in Iniz files.
Sorry I know the image size is big - I failed after 30 mins of trying different approaches to make it smaller 🤷 .
=> Add Video Tutorial to README
